/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.pixhan.proventas.vista;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.pixhan.negocio.DatosClases;
import net.pixhan.negocio.UtilNegocio;
import net.pixhan.utilidades.ValidacionCadenas;

/**
 *
 * @author Baloo
 */
public class JFAddClaseTercearia extends javax.swing.JFrame {

    private static Connection conexionNegocio;
    private ValidacionCadenas validacion = new ValidacionCadenas();
    private static final int TAMANIO_MAX_NOMBRE_CLASE_TERCEARIA = 30;
    private static final int TAMANIO_MAX_DESCRIPCION_CLASE_TERCEARIA = 45;
    private static ArrayList<DatosClases> datosClases;
    /**
     * Creates new form JFAddClaseTerciaria
     */
    public JFAddClaseTercearia( Connection conexionNegocio ) {
        this.conexionNegocio = conexionNegocio;
        initComponents();
        validacion.limitarCaracteres(this.txtDescripcionClaseTercearia, this.TAMANIO_MAX_DESCRIPCION_CLASE_TERCEARIA);
        validacion.limitarCaracteres(this.txtNombreClaseTercearia, this.TAMANIO_MAX_NOMBRE_CLASE_TERCEARIA);
        validacion.validarSoloLetras(this.txtDescripcionClaseTercearia);
        validacion.validarSoloLetras(this.txtNombreClaseTercearia);
        this.btnAdd_Clase.setMnemonic(KeyEvent.VK_ENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreClaseTercearia = new javax.swing.JTextField();
        txtDescripcionClaseTercearia = new javax.swing.JTextField();
        btnAdd_Clase = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cbClaseSecundaria = new javax.swing.JComboBox<DatosClases>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Clase Secundaria:");

        jLabel2.setText("Nombre Clase Tercearia:");

        jLabel3.setText("Descripción:");

        btnAdd_Clase.setMnemonic('O');
        btnAdd_Clase.setText("Añadir Clase");
        btnAdd_Clase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_ClaseActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbClaseSecundaria, 0, 130, Short.MAX_VALUE)
                            .addComponent(txtNombreClaseTercearia)
                            .addComponent(txtDescripcionClaseTercearia)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd_Clase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbClaseSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreClaseTercearia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDescripcionClaseTercearia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd_Clase)
                    .addComponent(btnCancelar))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdd_ClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_ClaseActionPerformed

        if ( !txtNombreClaseTercearia.getText().isEmpty() && !txtDescripcionClaseTercearia.getText().isEmpty() ) {        
        
        DatosClases datosClaseSeleccionada = (DatosClases) this.cbClaseSecundaria.getSelectedItem();

        if ( datosClaseSeleccionada != null ){        
            int idClasePrimaria = datosClaseSeleccionada.getIdClase();
            boolean existeError = true;
            try {
                existeError = UtilNegocio.agregarClaseSecundaria( idClasePrimaria, this.txtNombreClaseTercearia.getText(), this.txtDescripcionClaseTercearia.getText(), null);
                if ( existeError == true ){
                    System.out.println("Ha ocurrido un error");
                }
                else{
                    System.out.println("Sin errores");
                }    
            } catch (SQLException ex) {
                Logger.getLogger(JFAddClaseSecundaria.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            System.out.println("No puede añadir. No hay nada seleccionado");
        }
        }else{
            System.out.println("No soportado");
        }

        
// TODO add your handling code here:
    }//GEN-LAST:event_btnAdd_ClaseActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void rellenarClases(){
        this.cbClaseSecundaria.removeAllItems();
        int tamanio = 0;
        //Implementacion de lo demás del código
        try{
            datosClases = UtilNegocio.devolverNombresClases("1", conexionNegocio );
            tamanio = datosClases.size();
            for ( int indice = 0; indice < tamanio; indice++ ){
                cbClaseSecundaria.addItem( datosClases.get(indice) );
            }
        }catch (SQLException e){
            e.getErrorCode();
        }
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAddClaseTercearia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAddClaseTercearia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAddClaseTercearia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAddClaseTercearia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAddClaseTercearia( null ).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd_Clase;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<DatosClases> cbClaseSecundaria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtDescripcionClaseTercearia;
    private javax.swing.JTextField txtNombreClaseTercearia;
    // End of variables declaration//GEN-END:variables
}
