/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.pixhan.proventas.vista;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.pixhan.negocio.DatosClases;
import net.pixhan.negocio.UtilNegocio;
import net.pixhan.utilidades.ValidacionCadenas;

/**
 *
 * @author Baloo
 */
public class JFAddClasePrimaria extends javax.swing.JFrame {

    private static Connection conexionNegocio;
    private ValidacionCadenas validacion = new ValidacionCadenas();
    private static final int TAMANIO_MAX_NOMBRE_CLASE_PRIMARIA = 30;
    private static final int TAMANIO_MAX_DESCRIPCION_CLASE_PRIMARIA = 45;
    private static ArrayList<DatosClases> datosClases;
    
    /**
     * Creates new form JFAddClasePrimaria
     */
    public JFAddClasePrimaria( Connection conexionNegocio ) {
        this.conexionNegocio = conexionNegocio;
        initComponents();
        validacion.limitarCaracteres(txtDescripcionClasePrimaria, this.TAMANIO_MAX_DESCRIPCION_CLASE_PRIMARIA);
        validacion.limitarCaracteres(txtNombreClasePrimaria, this.TAMANIO_MAX_NOMBRE_CLASE_PRIMARIA);
        validacion.validarSoloLetras(txtDescripcionClasePrimaria);
        validacion.validarSoloLetras(txtNombreClasePrimaria);
        rellenarClases();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAdd_Clase = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtNombreClasePrimaria = new javax.swing.JTextField();
        txtDescripcionClasePrimaria = new javax.swing.JTextField();
        cbAreaNegocio = new javax.swing.JComboBox<DatosClases>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Area De Negocio:");

        jLabel2.setText("Nombre De Clase Primaria:");

        jLabel3.setText("Descripción");

        btnAdd_Clase.setText("Añadir Area");
        btnAdd_Clase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_ClaseActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        cbAreaNegocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAreaNegocioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(4, 4, 4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(47, 47, 47)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNombreClasePrimaria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(txtDescripcionClasePrimaria, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbAreaNegocio, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd_Clase)
                        .addGap(54, 54, 54)
                        .addComponent(btnCancelar)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbAreaNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreClasePrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDescripcionClasePrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd_Clase)
                    .addComponent(btnCancelar))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbAreaNegocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAreaNegocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAreaNegocioActionPerformed

    private void btnAdd_ClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_ClaseActionPerformed
        // TODO add your handling code here:

        if ( !txtNombreClasePrimaria.getText().isEmpty() && !txtDescripcionClasePrimaria.getText().isEmpty() ) {

        DatosClases datosClaseSeleccionada = (DatosClases) this.cbAreaNegocio.getSelectedItem();

        if ( datosClaseSeleccionada != null ){
            try {
                int idAreaNegocio = datosClaseSeleccionada.getIdClase();
                System.out.print("Aquí va la comprobación: ");
                System.out.println(idAreaNegocio);
                boolean existeError = true;
                existeError = UtilNegocio.agregarClasePrimaria( idAreaNegocio, this.txtNombreClasePrimaria.getText(), this.txtDescripcionClasePrimaria.getText(), conexionNegocio);
                if ( existeError == false ){
                    System.out.println("Operacion realizada con exito");
                    this.dispose();
                }
                else{
                    System.out.println("Ha ocurrido un error");
                }
            } catch (SQLException ex ) {
                Logger.getLogger(JFAddClasePrimaria.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            System.out.println("No se puede realizar la accion. No hay nada seleccionado");
        }
        }else{
            System.out.println("Operacion no admitida");
        }
    }//GEN-LAST:event_btnAdd_ClaseActionPerformed

    private void rellenarClases(){
        this.cbAreaNegocio.removeAllItems();
        int tamanio = 0;
        String nombreClase;
        //Implementacion de lo demás del código
        try{
            datosClases = UtilNegocio.devolverNombresClases("a", conexionNegocio );
            tamanio = datosClases.size();
            for ( int indice = 0; indice < tamanio; indice++ ){
                cbAreaNegocio.addItem( datosClases.get(indice) );
                System.out.println( datosClases.get(indice).getNombreClase() );
            }
        }catch (SQLException e){
            e.getErrorCode();
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAddClasePrimaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAddClasePrimaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAddClasePrimaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAddClasePrimaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAddClasePrimaria( null ).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd_Clase;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<DatosClases> cbAreaNegocio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtDescripcionClasePrimaria;
    private javax.swing.JTextField txtNombreClasePrimaria;
    // End of variables declaration//GEN-END:variables
}
